apiVersion: v1
kind: Pod
metadata:
  name: nginx-kata-qemu
  labels:
    app: nginx
    runtime: kata-qemu
spec:
  runtimeClassName: kata-qemu
  nodeSelector:
    kubernetes.io/hostname: k8s-node-1  # Deploy on node-1
  containers:
  - name: nginx
    image: nginx:1.27-alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "250m"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-kata-qemu-svc
spec:
  selector:
    app: nginx
    runtime: kata-qemu
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
