---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-kata-fc
  labels:
    app: nginx
    runtime: kata-fc
spec:
  # Use Kata+Firecracker runtime
  runtimeClassName: kata-fc

  # Schedule on k8s-node-2 where Kata is installed
  nodeSelector:
    kubernetes.io/hostname: k8s-node-2

  containers:
  - name: nginx
    image: nginx:1.27-alpine
    ports:
    - containerPort: 80
      name: http
      protocol: TCP

    # Resource requests (actual container needs, not including microVM overhead)
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"

    # Health probes
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3

    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3

  restartPolicy: Always
  dnsPolicy: ClusterFirst
---
# Service to expose nginx
apiVersion: v1
kind: Service
metadata:
  name: nginx-kata-fc-svc
  labels:
    app: nginx
    runtime: kata-fc
spec:
  type: NodePort
  selector:
    app: nginx
    runtime: kata-fc
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
